baseURL = "https://abdulrehmansaqib.github.io/mymind.github.io/"
languageCode = "en-us"
title = "MyMind"

[params]
description = "Open your mind"
dateFormat = "Jan 2, 2006"

[taxonomies]
category = "categories"
author = "authors"


